name: CSharp App Release

on: workflow_dispatch

jobs:
  release:
    uses: zepben/.github/.github/workflows/csharp-app-release.yml@main
    with:
      test_files: data-access-layer-test\bin\Release\data-access-layer-test.dll
      version_file: ednar-reporting-service/Properties/AssemblyInfo.cs
      changelog: docs/release_notes.md
    secrets: inherit