name: Maven App Snapshot

on: workflow_dispatch

jobs:
  snapshot:
    uses: zepben/.github/.github/workflows/maven-app-snapshot.yml@main
    with:
      private: true
      product-key: "<some-product-key>"   # Must be unique
    secrets: inherit
    
