name: Maven Library Snapshot

on:
  push:
    branches:
      - main
      - LTS/*
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/maven-lib-snapshot.yml@main
    with:
      private: true
      product-key: "<some-product-key>"   # Must be unique
      product-repo: "<some-product-repo>"
    secrets: inherit
