name: Maven Build

on: 
  push:
    branches:
      - main
      - LTS/*
      - hotfix/*
  pull_request:
  workflow_dispatch:

jobs:
  run:
    uses: zepben/.github/.github/workflows/maven-build.yml@main
    secrets: inherit

