name: NPM Lib Snapshot Release

on: 
  workflow_dispatch:
  push: 
    branches:
      - main
      - LTS/*
      - hotfix/*

jobs:
  run:
    uses: zepben/.github/.github/workflows/npm-lib-snapshot.yml@main
    with:
      product-key: "<some-product-key>"   # Must be unique
    secrets: inherit
