name: Build Sealed Docker Image
on:
  workflow_call:
    inputs:
      version_tag:
        description: Precomputed version tag to use as a Docker image tag
        type: string
        default: ''
      latest_tag:
        description: If the image should be tagged with 'latest'. Should only be used for release builds
        type: boolean
        default: false
      edge_tag:
        description: If the image should be tagged with 'edge'. Should only be used for snapshot builds
        type: boolean
        default: false
      push_image:
        description: If the image should be pushed to GHCR
        type: boolean
        default: false
      dockerfile:
        description: Override the Dockerfile in use
        type: string
        default: 'Dockerfile'
      build-args:
        description: Build args for building the Dockerfile
        required: false
        type: string
        default: ''
      commit:
        description: Override the commit to build the container on
        required: false
        type: string
        default: ''
    secrets:
      CI_GITHUB_TOKEN:
        required: true

env:
  REGISTRY_URL: "ghcr.io/${{ github.repository }}"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.commit }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CI_GITHUB_TOKEN }}

      # Priority sorting determines the tag used in the OCI label
      # The current order preferences the version, then commit, then any special tags
      # We always push a commit based tag
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_URL }}
          tags: |
            type=sha,format=short,priority=200
            type=sha,format=long,priority=220
            type=raw,value=${{ inputs.version_tag }},enable=${{ inputs.version_tag != '' }},priority=900
            type=raw,value=edge,enable=${{ inputs.edge_tag }},priority=100
            type=raw,value=latest,enable=${{ inputs.latest_tag }},priority=100

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ inputs.push_image }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ${{ inputs.dockerfile }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.build-args }}
