name: Internal Dependecy Check

on: 
  workflow_call:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review]


jobs:

  check_deps:
    runs-on: ubuntu-latest
    container: zepben/pipeline-java-ewb
    env:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ env.GITHUB_TOKEN }}

    - name: Work around git permission issue
      run: |
        dname=$(echo ${{github.repository}} | cut -d'/' -f2)
        git config --global --add safe.directory /__w/$dname/$dname
      shell: sh

    - run: |
        updates_found=false
        superpom=$(mvn -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD  versions:display-parent-updates | grep ":evolve-super-pom" | sed -e "s/^.*INFO.*c/c/g")
        if [ z"${superpom}" != "z" ]; then
          msg="${msg}\rA superpom update available: ${superpom}\r" 
          updates_found=true
        fi

        versions=$(mvn -Dserver.repo.url=$NEXUS_MAVEN_REPO -Dserver.username=$NEXUS_USERNAME -Dserver.password=$NEXUS_PASSWORD versions:display-dependency-updates | grep "com.zepben:" | sed -e "s/^.*INFO.*c/c/g")
        if [ z"${versions}" != "z" ]; then
          msg="${msg}\rVersion(s) updates are available: ${versions}\r" 
          updates_found=true
        fi

        if [ ${updates_found} == true ]; then
          echo -e "${mgs}" | gh pr comment ${{ github.event.pull_request.number }} --body-file -
        fi
      shell: bash

