name: Internal Dependency Check

on: 
  workflow_call:

jobs:

  check_deps:
    runs-on: ubuntu-latest
    container: zepben/pipeline-java-ewb
    env:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
      NEXUS_MAVEN_REPO: ${{ secrets.NEXUS_MAVEN_REPO }}
      NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
      NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
    steps:

    - uses: actions/checkout@v4
      with:
        token: ${{ env.GITHUB_TOKEN }}

    - name: Work around git permission issue
      run: |
        dname=$(echo ${{github.repository}} | cut -d'/' -f2)
        git config --global --add safe.directory /__w/$dname/$dname
      shell: sh

    - name: Check for updates to superpom and dependencies
      run: |
        mvn_version_args=("-Dserver.repo.url=$NEXUS_MAVEN_REPO" "-Dserver.username=$NEXUS_USERNAME" "-Dserver.password=$NEXUS_PASSWORD" "-Dversions.outputLineWidth=120")
        alias isolate_version_text="sed -e 's/\x1b\[[0-9;]*m//g' -e 's/^.*INFO.\s*//'"  # first substitution removes ANSI escape sequences
        updates_found=false
        msg="The following updates are available for this repository:"
        superpom=$(mvn "${mvn_version_args[@]}" versions:display-parent-updates | grep ":evolve-super-pom" | isolate_version_text)
        if [ z"${superpom}" != "z" ]; then
          msg="${msg}\n\nA superpom update available: \n\`\`\`\n${superpom}\n\`\`\`\n" 
          updates_found=true
        fi

        # two spaces in regex needed to filter out header line
        versions=$(mvn "${mvn_version_args[@]}" versions:display-dependency-updates | grep "  com.zepben" | isolate_version_text)
        if [ z"${versions}" != "z" ]; then
          msg="${msg}\nVersion(s) updates are available: \n\`\`\`\n${versions}\n\`\`\`\n" 
          updates_found=true
        fi

        if [ ${updates_found} == true ]; then
          echo -e "${msg}" | gh pr comment ${{ github.event.pull_request.number }} --body-file -
        fi
      shell: bash

