name: Maven Build OSS

on: 
  workflow_call:


jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: zepben/pipeline-java
    outputs: 
      docs: ${{ steps.docs.present}}
    steps:
      - uses: actions/checkout@v4

      - name: Cache licence-check
        uses: actions/cache@v3
        with:
          path: /lc
          key: lcc

      - name: Check licence
        uses: zepben/licence-check-action@main
        with:
          LC_URL: ${{ secrets.LC_URL }}

      - name: Cache maven deps
        uses: actions/cache@v2
        with:
          path: /maven
          key: maven

      - name: Maven build and test
        id: build
        run: mvn clean test -P '!zepben-maven' -f pom.xml
        shell: bash

      - name: Upload coverage to Codecov
        if: steps.build.outcome == 'success'
        uses: codecov/codecov-action@v2

      - name: Check if docs present
        id: docs
        run: |
          if [ -d docs ]; then
            echo "present=yes" >> $GITHUB_ENV
          fi

  build-docs:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ needs.build-and-test.outputs.docs == 'yes' }}
    container: node:16-alpine
    steps:

      - uses: actions/checkout@v3

      - name: Build docusaurus
        id: build
        uses: zepben/docusaurus-action@main
        with:
          TAG-AND-RELEASE: false
          NPM_REPO: ${{ secrets.NPM_REPO }}
          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        continue-on-error: true
