name: NPM Static App Release

on:
  workflow_call:

    secrets:
      NEXUS_NPM_DEV_REPO:
        required: true
      CI_NPM_DEV_TOKEN:
        required: true

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    container: node:24-alpine
    env:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
    steps:
      - name: Install Dependencies
        run: |
          apk add jq tar alpine-conf git bash python3

      - name: Cache nodejs deps
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: npm

       # Checkout the .github repo itself, into a subfolder
      - name: Checkout .github repo
        uses: actions/checkout@v7
        with:
          repository: ${{ github.workflow_repository }}
          ref: ${{ github.workflow_sha }}
          path: central

      - uses: actions/checkout@v7
        with:
          token: ${{ env.GITHUB_TOKEN }}

      - name: Set timezone to Australia/ACT
        run: |
          setup-timezone -z Australia/ACT

      - name: Work around git permission issue
        run: |
          dname=$(echo ${{github.repository}} | cut -d'/' -f2)
          git config --global --add safe.directory /__w/$dname/$dname
        shell: sh

      - name: create .npmrc
        run: |
          rm -rf .npmrc
          echo "@zepben:registry=https://${{ secrets.NEXUS_NPM_DEV_REPO }}" >> .npmrc
          echo "//${{ secrets.NEXUS_NPM_DEV_REPO }}:_authToken=${{ secrets.CI_NPM_DEV_TOKEN }}" >> .npmrc
          echo "\n" >> .npmrc

      - name: Update dev version
        run: |
          # Update the version to dev
          shopt -s nocasematch
          version=$(jq -r .version package.json)

          # Clickup Ticket regex 
          regex="(PROJ|EWB|EDNAR|BD|DEV|OPS|SUPPORT)-[0-9]{1,5}"
          # Detect TaskID
          if [[ $GITHUB_REF =~ $regex ]]; then
              # ${BASH_REMATCH[0]} contains the exact matched identifier
              ticket=${BASH_REMATCH[0]}
              echo "   -------------------------   "
              echo "   Found the ticket: $ticket   "
              echo "   -------------------------   "
          else
              ticket=$(git rev-parse --short HEAD)
              echo "-----------------------------------------------------------------------------"
              echo "    No tickets were found for this branch, using sha '$ticket' for version   "
              echo "-----------------------------------------------------------------------------"
          fi
          new_version=$version-$ticket    
          jq --arg VERSION $new_version '.version = $VERSION' package.json
        shell: bash

      - name: Add git info to the package
        run: |
          python3 central/tools/update_npm_project_git.py

      - name: build and deploy
        id: build
        run: |
          npm run ci --unsafe-perm
          npm run deploy
