name: Build

on:
  workflow_call:
    inputs:
      private:
        description: 'Calling workflow from a private repo'
        required: false
        type: boolean
        default: true
      licencecheck:
        description: 'Need to check licence headers/files'
        required: false
        type: boolean
        default: false
      sourcepath:
        description: 'Path to source directory (used for licence check)'
        required: false
        type: string
        default: "src"
    secrets:
      LC_URL: 
        required: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: python:3.9
    outputs: 
      docs: ${{ steps.docs.outputs.present }}
    env:
      LICENCE_CHECK: ${{ inputs.licencecheck }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install tox

      - name: Cache licence-check
        if: ${{ env.LICENCE_CHECK == true }}
        uses: actions/cache@v3
        with:
          path: /lc
          key: lcc

      - name: Check licence
        if: ${{ env.LICENCE_CHECK == true }}
        uses: zepben/licence-check-action@main
        with:
          LC_URL: ${{ secrets.LC_URL }}
          PATH: ${{ inputs.sourcepath }}

      - name: Build and test
        run: |
          tox
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false

      - name: Check if docs present
        id: docs
        run: |
          exist=no
          if [ -d docs ]; then
            exist=yes
          fi
          echo "present=$exist" >> "${GITHUB_OUTPUT}"

  build-docs:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: ${{ hashFiles('docs/package-lock.json', 'docs/package.json') != "" }}
    container: node:16-alpine
    steps:

      - uses: actions/checkout@v3

      - name: Build docusaurus
        id: build
        uses: zepben/docusaurus-action@main
        with:
          TAG-AND-RELEASE: false
          NPM_REPO: ${{ secrets.NPM_REPO }}
          NPM_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
        continue-on-error: true
