name: Build

on:
  workflow_call:
    inputs:
      private:
        description: 'Calling workflow from a private repo'
        required: false
        type: boolean
        default: true
      licencecheck:
        description: 'Need to check licence headers/files'
        required: false
        type: boolean
        default: false
      sourcepath:
        description: 'Path to source directory (used for licence check)'
        required: false
        type: string
        default: "src"
    secrets:
      LC_URL: 
        required: false

jobs:
  check-licence-and-test:
    runs-on: ubuntu-latest
    container: python:3.7
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install tox

      - name: Cache licence-check
        if: ${{ env.LICENCE_CHECK }}
        uses: actions/cache@v3
        with:
          path: /lc
          key: lcc

      - name: Check licence
        if: ${{ env.LICENCE_CHECK }}
        uses: zepben/licence-check-action@main
        with:
          LC_URL: ${{ secrets.LC_URL }}
          PATH: ${{ inputs.sourcepath }}

      - name: Build and test
        run: |
          tox
        shell: bash

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: false
